// ICAO airline (operator) code → display name. The callsign's first three
// letters are the operator code (KAL902 → KAL → Korean Air), so we can identify
// the airline straight from the callsign — no external lookup, and it works even
// when adsbdb has no route for the flight. Names are Korean where the carrier is
// well known in Korea, otherwise the English brand.
//
// Not exhaustive (there are thousands of operators); this covers the major
// passenger and cargo airlines that make up the bulk of worldwide traffic.

export const AIRLINES: Record<string, string> = {
  // Korea
  KAL: '대한항공',
  AAR: '아시아나항공',
  JJA: '제주항공',
  JNA: '진에어',
  TWB: '티웨이항공',
  ABL: '에어부산',
  ASV: '에어서울',
  EOK: '에어프레미아',
  // China
  CCA: '중국국제항공',
  CES: '중국동방항공',
  CSN: '중국남방항공',
  CHH: '하이난항공',
  CSC: '쓰촨항공',
  CXA: '샤먼항공',
  CDG: '산둥항공',
  CSH: '상하이항공',
  CQH: '춘추항공',
  CSZ: '선전항공',
  CBJ: '수도항공',
  DKH: '준야오항공',
  GCR: '톈진항공',
  CUA: '중국연합항공',
  OKA: '오케이항공',
  LKE: '럭키에어',
  HXA: '화샤항공',
  EPA: '둥하이항공',
  CKK: '중국화물항공',
  CYZ: '중국우정항공',
  // Hong Kong / Taiwan
  CPA: '캐세이퍼시픽',
  HDA: '캐세이드래곤',
  CAL: '중화항공',
  EVA: '에바항공',
  CRK: '홍콩항공',
  HKE: '홍콩익스프레스',
  AHK: '에어홍콩',
  UIA: '유니항공',
  TTW: '타이거에어대만',
  // Japan
  JAL: '일본항공',
  ANA: '전일본공수',
  APJ: '피치항공',
  JJP: '제트스타재팬',
  SKY: '스카이마크',
  ADO: '에어두',
  SNJ: '솔라시드에어',
  SFJ: '스타플라이어',
  TZP: '집에어',
  IBX: 'IBEX항공',
  FDA: '후지드림항공',
  JAC: '일본에어코뮤터',
  RAC: '류큐에어코뮤터',
  ORC: '오리엔탈에어브리지',
  SJO: '스프링재팬',
  // Southeast Asia
  SIA: '싱가포르항공',
  THA: '타이항공',
  MAS: '말레이시아항공',
  AXM: '에어아시아',
  GIA: '가루다인도네시아',
  PAL: '필리핀항공',
  CEB: '세부퍼시픽',
  VJC: '비엣젯항공',
  HVN: '베트남항공',
  TGW: '스쿠트',
  JSA: '젯스타아시아',
  BKP: '방콕항공',
  TVJ: '타이비엣젯',
  THD: '타이스마일',
  LNI: '라이온에어',
  BTK: '바틱에어',
  CTV: '시티링크',
  MXD: '바틱에어말레이시아',
  RBA: '로열브루나이',
  MAI: '미얀마국제항공',
  KNA: '캄보디아앙코르항공',
  // India / Middle East
  AIC: '에어인디아',
  IGO: '인디고',
  UAE: '에미레이트항공',
  QTR: '카타르항공',
  ETD: '에티하드항공',
  SVA: '사우디아',
  THY: '터키항공',
  ELY: '엘알',
  // Europe
  BAW: '영국항공',
  DLH: '루프트한자',
  AFR: '에어프랑스',
  KLM: 'KLM 네덜란드항공',
  IBE: '이베리아항공',
  AZA: 'ITA 항공',
  SWR: '스위스국제항공',
  AUA: '오스트리안항공',
  SAS: '스칸디나비아항공',
  FIN: '핀에어',
  TAP: 'TAP 포르투갈항공',
  VIR: '버진애틀랜틱',
  EIN: '에어링구스',
  RYR: '라이언에어',
  EZY: '이지젯',
  WZZ: '위즈에어',
  VLG: '부엘링',
  NAX: '노르웨이지안',
  AEE: '에게안항공',
  LOT: 'LOT 폴란드항공',
  CSA: '체코항공',
  // North America
  AAL: '아메리칸항공',
  UAL: '유나이티드항공',
  DAL: '델타항공',
  SWA: '사우스웨스트항공',
  JBU: '제트블루',
  ASA: '알래스카항공',
  NKS: '스피릿항공',
  FFT: '프론티어항공',
  ACA: '에어캐나다',
  WJA: '웨스트젯',
  // Latin America
  AMX: '아에로멕시코',
  LAN: '라탐항공',
  TAM: '라탐 브라질',
  AVA: '아비앙카',
  GLO: '골 항공',
  AZU: '아줄 항공',
  // Oceania
  QFA: '콴타스',
  JST: '제트스타',
  VOZ: '버진오스트레일리아',
  ANZ: '에어뉴질랜드',
  // Africa
  ETH: '에티오피아항공',
  MSR: '이집트항공',
  RAM: '로얄에어모로코',
  SAA: '남아프리카항공',
  KQA: '케냐항공',
  // Cargo
  FDX: '페덱스',
  UPS: 'UPS',
  GTI: '아틀라스항공',
  GEC: '루프트한자카고',
  CLX: '카고룩스',
  CKS: '칼리타항공',
  NCA: '니혼카고',
  CAO: '에어차이나카고',
  PAC: '폴라에어카고',
  BOX: '에어로로직',
  CJT: '카고젯',
  SQC: '싱가포르항공카고',
  ABW: '에어브릿지카고',
  // South Asia
  ALK: '스리랑카항공',
  PIA: '파키스탄국제항공',
  BBC: '비만방글라데시항공',
  SEJ: '스파이스젯',
  AKJ: '아카사에어',
  // Middle East
  ABY: '에어아라비아',
  FDB: '플라이두바이',
  OMA: '오만항공',
  GFA: '걸프에어',
  KAC: '쿠웨이트항공',
  RJA: '로열요르단항공',
  MEA: '중동항공',
  IRA: '이란항공',
  PGT: '페가수스항공',
  SXS: '선익스프레스',
  // Europe (extra)
  EWG: '유로윙스',
  CFG: '콘도르',
  TOM: 'TUI항공',
  BEL: '브뤼셀항공',
  BTI: '에어발틱',
  ICE: '아이슬란드에어',
  TRA: '트란사비아',
  TVF: '트란사비아프랑스',
  EXS: '제트투',
  AEA: '에어에우로파',
  ANE: '에어노스트룸',
  VOE: '볼로테아',
  OAL: '올림픽항공',
  CTN: '크로아티아항공',
  ROT: '타롬',
  LGL: '룩스에어',
  KLC: 'KLM시티호퍼',
  CLH: '루프트한자시티라인',
  NSZ: '노르스애틀랜틱',
  EJU: '이지젯유럽',
  EZS: '이지젯스위스',
  WUK: '위즈에어UK',
  RUK: '라이언에어UK',
  // Russia / Central Asia
  AFL: '아에로플로트',
  SDM: '로시야항공',
  SBI: 'S7항공',
  SVR: '우랄항공',
  PBD: '포베다',
  UTA: 'UT에어',
  KZR: '에어아스타나',
  UZB: '우즈베키스탄항공',
  // North America (extra)
  HAL: '하와이안항공',
  SKW: '스카이웨스트',
  RPA: '리퍼블릭항공',
  EDV: '엔데버에어',
  ENY: '엔보이에어',
  JIA: 'PSA항공',
  QXE: '호라이즌에어',
  AWI: '에어위스콘신',
  GJS: '고젯',
  PDT: '피드몬트항공',
  MXY: '브리즈항공',
  SCX: '선컨트리항공',
  AAY: '얼리전트에어',
  POE: '포터항공',
  TSC: '에어트랜샛',
  JZA: '재즈항공',
  ROU: '에어캐나다루즈',
  FLE: '플레어항공',
  VOI: '볼라리스',
  VIV: '비바아에로부스',
  SLI: '아에로멕시코커넥트',
  // Latin America (extra)
  ARG: '아르헨티나항공',
  CMP: '코파항공',
  SKU: '스카이항공',
  JAT: '젯스마트',
  // Africa (extra)
  DAH: '알제리항공',
  TAR: '튀니스에어',
  RWD: '르완다에어',
  // Oceania (extra)
  RXA: '렉스항공',
  FJI: '피지항공',
  // Business / fractional operators. Their callsigns look like an airline's
  // because they are one — a fleet flown on demand rather than to a timetable,
  // which is exactly why a route database has nothing for them.
  NJE: '넷제트유럽',
  EJA: '넷제트',
  EJM: '이그제큐티브젯매니지먼트',
  LXJ: '플렉스젯',
  VJT: '비스타젯',
  // Cargo (extra)
  ABX: 'ABX에어',
  ATN: '에어트랜스포트인터내셔널',
  DHK: 'DHL에어',
  BCS: 'DHL유럽',
  TAY: 'ASL벨기에',
  ABR: 'ASL아일랜드',
  SWT: '스위프트에어',
  AZG: '실크웨이웨스트',
  VDA: '볼가드네프르',
  YZR: '양쯔강항공'
}

/** Airline name from a callsign's 3-letter operator prefix, or null if unknown. */
export function airlineFromCallsign(callsign?: string | null): string | null {
  const cs = (callsign ?? '').toUpperCase().trim()
  if (!/^[A-Z]{3}/.test(cs)) return null
  return AIRLINES[cs.slice(0, 3)] ?? null
}
